/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Query RDAP information for a domain name.
 *
 * @param domainName - Domain name (e.g. "example.com", Unicode IDNs supported)
 * @returns Normalised RDAP domain object
 */
export declare function domain(domainName: string): Promise<any>
/**
 * Query RDAP information for an IP address (IPv4 or IPv6).
 *
 * @param ipAddress - IP address (e.g. "8.8.8.8", "2001:4860:4860::8888")
 * @returns Normalised RDAP IP network object
 */
export declare function ip(ipAddress: string): Promise<any>
/**
 * Query RDAP information for an Autonomous System Number.
 *
 * @param asnValue - ASN number or prefixed form (e.g. "15169", "AS15169")
 * @returns Normalised RDAP autnum object
 */
export declare function asn(asnValue: string): Promise<any>
/**
 * Query RDAP information for a nameserver hostname.
 *
 * @param hostname - Nameserver hostname (e.g. "ns1.google.com")
 * @returns Normalised RDAP nameserver object
 */
export declare function nameserver(hostname: string): Promise<any>
/**
 * Query RDAP information for an entity (contact / registrar).
 *
 * Entities have no global bootstrap registry — an explicit server URL is required.
 *
 * @param handle    - Entity handle (e.g. "ARIN-HN-1")
 * @param serverUrl - RDAP server base URL (e.g. "https://rdap.arin.net/registry")
 * @returns Normalised RDAP entity object
 */
export declare function entity(handle: string, serverUrl: string): Promise<any>
